packages:
  - packages/**
  - config
  - playgrounds/**

catalog:
  "@typescript/native-preview": beta
  "@types/node": 24.2.0
  "@vitest/browser-playwright": 4.0.4
  "@vitest/coverage-v8": 4.0.4
  eslint: 9.38.0
  oxfmt: 0.41.0
  oxlint: 1.51.0
  oxlint-tsgolint: 0.16.0
  rlse.ts: 0.0.6
  tsdown: 0.22.0
  typescript: 6.0.3
  vitest: 4.0.4
