import { execFileSync } from "node:child_process";
import { defineConfig, steps, z, type RlseContext, type RlseFlowStep } from "rlse.ts";

const packages = [
  "@dathra/shared",
  "@dathra/reactivity",
  "@dathra/store",
  "@dathra/transformer",
  "@dathra/runtime",
  "@dathra/plugin",
  "@dathra/components",
  "@dathra/core",
];

const gitUser = {
  name: "github-actions[bot]",
  email: "41898282+github-actions[bot]@users.noreply.github.com",
};

const nextVersion = ({ results }: RlseContext) => results.findStep("calculateNextSemver").nextVersion;
const latestPackage = ({ results }: RlseContext) => results.findStep("resolvePackage");
const releaseFiles = () => ["CHANGELOG.md", ...packages.map((packageName) => packageJsonPath(packageName))];
const releaseTag = (context: RlseContext) => `v${nextVersion(context)}`;
const releaseBranch = (context: RlseContext) => `release/packages-${releaseTag(context)}`;
const isPrereleaseVersion = (version: string) => version.includes("-");
const packageJsonPath = (packageName: string) => `packages/${packageName.replace("@dathra/", "")}/package.json`;
const releaseNotes = (version: string) => `Release ${version} for all public packages.`;

const runPackageRelease = (packageName: string): RlseFlowStep => ({
  name: "runPackageRelease",
  run: (context) => {
    const version = nextVersion(context);
    const args = ["--filter", packageName, "exec", "rlse", "--release-version", version];

    if (context.dryRun) {
      args.push("--skip-publish", "--dry-run");
    }

    execFileSync("pnpm", args, { cwd: context.cwd, stdio: "inherit" });
    return { packageName, version, dryRun: context.dryRun };
  },
});

const createReleasePullRequest = (): RlseFlowStep => ({
  name: "createReleasePullRequest",
  run: (context) => {
    const version = nextVersion(context);

    if (context.dryRun) {
      console.info(`[dry-run] Skip gh pr create for v${version}`);
      return { version, dryRun: true, created: false };
    }

    execFileSync(
      "gh",
      [
        "pr",
        "create",
        "--title",
        `Release v${version}`,
        "--body",
        `Release v${version}\n\nThis PR was automatically generated by the release workflow.`,
        "--base",
        "main",
        "--head",
        releaseBranch(context),
        "--reviewer",
        "takuma-ru",
        "--label",
        ":rocket: release",
      ],
      { cwd: context.cwd, stdio: "inherit" },
    );

    return { version, dryRun: false, created: true };
  },
});

const pushReleaseBranch = (): RlseFlowStep => ({
  name: "pushReleaseBranch",
  run: (context) => {
    const branch = releaseBranch(context);

    if (context.dryRun) {
      console.info(`[dry-run] Skip git push --set-upstream origin ${branch}`);
      return { branch, dryRun: true, pushed: false };
    }

    execFileSync("git", ["push", "--set-upstream", "origin", branch], { cwd: context.cwd, stdio: "inherit" });
    return { branch, dryRun: false, pushed: true };
  },
});

const pushTag = (): RlseFlowStep => ({
  name: "pushTag",
  run: (context) => {
    const tag = releaseTag(context);

    if (context.dryRun) {
      console.info(`[dry-run] Skip git push origin ${tag}`);
      return { tag, dryRun: true, pushed: false };
    }

    execFileSync("git", ["push", "origin", tag], { cwd: context.cwd, stdio: "inherit" });
    return { tag, dryRun: false, pushed: true };
  },
});

export default defineConfig({
  args: z.object({
    level: z.enum(["patch", "minor", "major", "preup"]).default("patch"),
    pre: z.boolean().default(false),
  }),
  flow: ({ args }) => [
    steps.configureGitUser(gitUser),
    steps.resolvePackage({ name: "@dathra/shared" }),
    steps.resolvePublishedVersion({
      packageName: (context) => latestPackage(context).packageName,
      fallbackVersion: (context) => String(latestPackage(context).packageJson.version ?? "0.0.0"),
    }),
    steps.calculateNextSemver({
      currentVersion: ({ results }) => results.findStep("resolvePublishedVersion").currentVersion,
      packageJson: (context) => latestPackage(context).packageJson,
      level: args.level,
      pre: args.pre,
    }),
    steps.createReleaseBranch({ branch: releaseBranch }),
    ...packages.map(runPackageRelease),
    steps.updateChangelog({
      version: nextVersion,
      changes: (context) => [releaseNotes(nextVersion(context))],
    }),
    steps.stageFiles({ paths: releaseFiles }),
    steps.commit({ message: "Release packages" }),
    pushReleaseBranch(),
    createReleasePullRequest(),
    steps.tag({
      name: releaseTag,
      message: (context) => `Release ${releaseTag(context)}`,
    }),
    pushTag(),
    steps.githubRelease({
      tag: releaseTag,
      title: (context) => `Release ${releaseTag(context)}`,
      notes: (context) => releaseNotes(releaseTag(context)),
      prerelease: (context) => isPrereleaseVersion(nextVersion(context)),
    }),
  ],
});
