import { execFileSync, spawn } from "node:child_process";
import { defineConfig, steps, z, type RlseContext, type RlseFlowStep } from "rlse.ts";

const packages = [
  "@dathra/shared",
  "@dathra/reactivity",
  "@dathra/store",
  "@dathra/transformer",
  "@dathra/runtime",
  "@dathra/plugin",
  "@dathra/components",
  "@dathra/core",
];

const gitUser = {
  name: "github-actions[bot]",
  email: "41898282+github-actions[bot]@users.noreply.github.com",
};

const nextVersion = ({ results }: RlseContext) =>
  results.findStep("calculateNextSemver").nextVersion;
const latestPackage = ({ results }: RlseContext) => results.findStep("resolvePackage");
const releaseFiles = () => [
  "CHANGELOG.md",
  ...packages.map((packageName) => packageJsonPath(packageName)),
];
const releaseTag = (context: RlseContext) => `v${nextVersion(context)}`;
const isPrereleaseVersion = (version: string) => version.includes("-");
const packageJsonPath = (packageName: string) =>
  `packages/${packageName.replace("@dathra/", "")}/package.json`;
const releaseNotes = (version: string) => `Release ${version} for all public packages.`;
const packageKey = (packageName: string) => packageName.replace("@", "").replaceAll("/", "-");
const releaseBranch = steps.releaseBranchName({
  version: releaseTag,
  prefix: "release/packages",
  separator: "-",
  suffix: steps.env(["GITHUB_RUN_ID", "GITHUB_RUN_ATTEMPT"], { fallback: `local${Date.now()}` }),
});

const runPnpm = (args: string[], cwd: string) =>
  new Promise<void>((resolve, reject) => {
    const child = spawn("pnpm", args, { cwd, stdio: "inherit" });

    child.on("error", reject);
    child.on("exit", (code, signal) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(
        new Error(
          `pnpm ${args.join(" ")} failed with ${signal ? `signal ${signal}` : `exit code ${code}`}`,
        ),
      );
    });
  });

const runPackageVersioning = (packageName: string): RlseFlowStep => ({
  name: `runPackageVersioning:${packageKey(packageName)}`,
  run: (context) => {
    const version = nextVersion(context);
    const args = [
      "--filter",
      packageName,
      "exec",
      "rlse",
      "--release-version",
      version,
      "--skip-publish",
    ];

    if (context.dryRun) {
      args.push("--dry-run");
    }

    execFileSync("pnpm", args, { cwd: context.cwd, stdio: "inherit" });
    return { packageName, version, dryRun: context.dryRun, publishSkipped: true };
  },
});

const runPackagePublish = (packageName: string, dryRun: boolean): RlseFlowStep => ({
  name: `runPackagePublish:${packageKey(packageName)}`,
  run: (context) => {
    const version = nextVersion(context);
    const args = [
      "--filter",
      packageName,
      "exec",
      "rlse",
      "--release-version",
      version,
      "--publish-only",
    ];

    if (dryRun) {
      args.push("--dry-run");
    }

    return runPnpm(args, context.cwd).then(() => ({
      packageName,
      version,
      dryRun,
      published: !dryRun,
    }));
  },
});

const runPackagePublishes = (): RlseFlowStep => ({
  name: "runPackagePublishes",
  run: async (context) => {
    const parallelStep = steps.parallel({
      name: "runPackagePublishes:parallel",
      concurrency: 4,
      tasks: packages.map((packageName) => runPackagePublish(packageName, context.dryRun)),
    });

    const result = await parallelStep.run({ ...context, dryRun: false });
    return { ...result, dryRun: context.dryRun };
  },
});

const createReleasePullRequest = (): RlseFlowStep => ({
  name: "createReleasePullRequest",
  run: (context) => {
    const version = nextVersion(context);

    if (context.dryRun) {
      console.info(`[dry-run] Skip gh pr create for v${version}`);
      return { version, dryRun: true, created: false };
    }

    execFileSync(
      "gh",
      [
        "pr",
        "create",
        "--title",
        `Release v${version}`,
        "--body",
        `Release v${version}\n\nThis PR was automatically generated by the release workflow.`,
        "--base",
        "main",
        "--head",
        releaseBranch(context),
        "--reviewer",
        "takuma-ru",
        "--label",
        ":rocket: release",
      ],
      { cwd: context.cwd, stdio: "inherit" },
    );

    return { version, dryRun: false, created: true };
  },
});

export default defineConfig({
  args: z.object({
    level: z.enum(["patch", "minor", "major", "preup"]).default("patch"),
    pre: z.boolean().default(false),
  }),
  flow: ({ args }) => [
    steps.configureGitUser(gitUser),
    steps.resolvePackage({ name: "@dathra/shared" }),
    steps.resolvePublishedVersion({
      packageName: (context) => latestPackage(context).packageName,
      fallbackVersion: (context) => String(latestPackage(context).packageJson.version ?? "0.0.0"),
    }),
    steps.calculateNextSemver({
      currentVersion: ({ results }) => results.findStep("resolvePublishedVersion").currentVersion,
      packageJson: (context) => latestPackage(context).packageJson,
      level: args.level,
      pre: args.pre,
    }),
    steps.createReleaseBranch({ branch: releaseBranch, ifExists: "skip" }),
    ...packages.map(runPackageVersioning),
    steps.updateChangelog({
      version: nextVersion,
      changes: (context) => [releaseNotes(nextVersion(context))],
    }),
    steps.stageFiles({ paths: releaseFiles }),
    steps.commit({ message: ":rocket: release packages" }),
    steps.push({ branch: releaseBranch, setUpstream: true, ifExists: "skip" }),
    createReleasePullRequest(),
    steps.tag({
      name: releaseTag,
      message: (context) => `Release ${releaseTag(context)}`,
    }),
    steps.pushTag({ tag: releaseTag, ifExists: "skip" }),
    steps.githubRelease({
      tag: releaseTag,
      title: (context) => `Release ${releaseTag(context)}`,
      notes: (context) => releaseNotes(releaseTag(context)),
      prerelease: (context) => isPrereleaseVersion(nextVersion(context)),
    }),
    runPackagePublishes(),
  ],
});
