import { execFileSync } from "node:child_process";
import { defineConfig, steps, z, type RlseContext, type RlseFlowStep } from "rlse.ts";

const packages = [
  "@dathra/shared",
  "@dathra/reactivity",
  "@dathra/store",
  "@dathra/transformer",
  "@dathra/runtime",
  "@dathra/plugin",
  "@dathra/components",
  "@dathra/core",
];

const releaseBranch = `release/packages-${process.env.GITHUB_RUN_ID ?? "local"}`;
const gitUser = {
  name: "github-actions[bot]",
  email: "41898282+github-actions[bot]@users.noreply.github.com",
};

const nextVersion = ({ results }: RlseContext) => results.findStep("calculateNextSemver").nextVersion;
const latestPackage = ({ results }: RlseContext) => results.findStep("resolvePackage");

const packageReleaseSteps = (packageName: string): RlseFlowStep[] => [
  steps.resolvePackage({ name: packageName }),
  steps.writePackageVersion({
    packageJsonPath: (context) => latestPackage(context).packageJsonPath,
    version: nextVersion,
  }),
];

const packagePublishSteps = (packageName: string): RlseFlowStep[] => [
  steps.resolvePackage({ name: packageName }),
  steps.checkNpmPackageVersionAvailable({
    packageName: (context) => latestPackage(context).packageName,
    version: nextVersion,
  }),
  steps.publishNpmPackage({
    packageName: (context) => latestPackage(context).packageName,
    packageDir: (context) => latestPackage(context).packageJsonPath.replace(/\/package\.json$/, ""),
  }),
  steps.verifyPublishedNpmPackage({
    packageName: (context) => latestPackage(context).packageName,
    version: nextVersion,
  }),
];

const createReleasePullRequest = (): RlseFlowStep => ({
  name: "createReleasePullRequest",
  run: (context) => {
    const version = nextVersion(context);

    if (context.dryRun) {
      console.info(`[dry-run] Skip gh pr create for v${version}`);
      return;
    }

    execFileSync(
      "gh",
      [
        "pr",
        "create",
        "--title",
        `Release v${version}`,
        "--body",
        `Release v${version} This PR was automatically generated by the release workflow.`,
        "--base",
        "main",
        "--head",
        releaseBranch,
        "--reviewer",
        "takuma-ru",
        "--label",
        ":rocket: release",
      ],
      { cwd: context.cwd, stdio: "inherit" },
    );
  },
});

const pushReleaseTag = (): RlseFlowStep => ({
  name: "pushReleaseTag",
  run: (context) => {
    const tag = `v${nextVersion(context)}`;

    if (context.dryRun) {
      console.info(`[dry-run] Skip git push origin ${tag}`);
      return;
    }

    execFileSync("git", ["push", "origin", tag], { cwd: context.cwd, stdio: "inherit" });
  },
});

export default defineConfig({
  args: z.object({
    level: z.enum(["patch", "minor", "major", "preup"]).default("patch"),
    pre: z.boolean().default(false),
  }),
  flow: ({ args }) => [
    steps.configureGitUser(gitUser),
    steps.createReleaseBranch({ branch: releaseBranch }),
    steps.resolvePackage({ name: "@dathra/shared" }),
    steps.resolvePublishedVersion({
      packageName: (context) => latestPackage(context).packageName,
      fallbackVersion: (context) => String(latestPackage(context).packageJson.version ?? "0.0.0"),
    }),
    steps.calculateNextSemver({
      currentVersion: ({ results }) => results.findStep("resolvePublishedVersion").currentVersion,
      packageJson: (context) => latestPackage(context).packageJson,
      level: args.level,
      pre: args.pre,
    }),
    ...packages.flatMap(packageReleaseSteps),
    steps.runCommand("pnpm build"),
    steps.runCommand("pnpm fmt"),
    steps.stageFiles({ paths: () => ["."] }),
    steps.commit({ message: `Release packages`, skipIfNoChanges: true }),
    steps.tag({
      name: (context) => `v${nextVersion(context)}`,
      message: (context) => `Release v${nextVersion(context)}`,
    }),
    steps.push({ branch: releaseBranch, setUpstream: true }),
    createReleasePullRequest(),
    ...packages.flatMap(packagePublishSteps),
    pushReleaseTag(),
    steps.githubRelease({
      tag: (context) => `v${nextVersion(context)}`,
      title: (context) => `Release v${nextVersion(context)}`,
      prerelease: args.pre,
    }),
  ],
});
