name: CI

on:
  pull_request:
    paths:
      - packages/**
      - playgrounds/**
      - config/**
      - .github/actions/**
      - .github/workflows/ci*.yaml
      - .npmrc
      - mise.toml
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - docs/package.json
  push:
    branches:
      - main
    paths:
      - packages/**
      - playgrounds/**
      - config/**
      - .github/actions/**
      - .github/workflows/ci*.yaml
      - .npmrc
      - mise.toml
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - docs/package.json
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  fmt:
    uses: ./.github/workflows/ci-fmt.yaml

  lint:
    uses: ./.github/workflows/ci-lint.yaml

  typecheck:
    uses: ./.github/workflows/ci-typecheck.yaml

  test:
    uses: ./.github/workflows/ci-test.yaml

  e2e:
    uses: ./.github/workflows/ci-e2e.yaml
